name: Trigger auto deployment for aca-snapflow-web-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-snapflow-web-prod-AutoDeployTrigger-e25796a1-5262-425f-ac62-11c8736dbf33.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACASNAPFLOWWEBPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACASNAPFLOWWEBPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACASNAPFLOWWEBPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.ACASNAPFLOWWEBPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACASNAPFLOWWEBPROD_REGISTRY_PASSWORD }}
          containerAppName: aca-snapflow-web-prod
          resourceGroup: snapflow
          imageToBuild: ghcr.io/aca-snapflow-web-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


